export const coupleData = {
  groomName: 'Arjun',
  brideName: 'Priya',
  initials: 'AP',
  weddingDate: new Date('2024-12-15T18:00:00'),
  venue: {
    name: 'The Grand Ballroom',
    address: '123 Wedding Lane, Luxury City, Country',
    latitude: 28.6139,
    longitude: 77.2090,
    phone: '+1-800-WEDDING',
    website: 'https://example.com',
  },
  schedule: [
    {
      id: 1,
      time: '04:00 PM',
      title: 'Ceremony',
      description: 'Join us for the sacred ceremony',
      icon: 'heart',
      duration: '1 hour',
    },
    {
      id: 2,
      time: '05:30 PM',
      title: 'Welcome Cocktail',
      description: 'Light refreshments and mingling',
      icon: 'glass',
      duration: '30 mins',
    },
    {
      id: 3,
      time: '06:30 PM',
      title: 'Dinner Reception',
      description: 'Delicious multi-course dinner',
      icon: 'utensils',
      duration: '2 hours',
    },
    {
      id: 4,
      time: '08:30 PM',
      title: 'First Dance',
      description: 'First dance and toasts',
      icon: 'music',
      duration: '30 mins',
    },
    {
      id: 5,
      time: '09:00 PM',
      title: 'Dancing & Celebration',
      description: 'Dance the night away',
      icon: 'sparkles',
      duration: 'Till late',
    },
  ],
  loveStory: [
    {
      id: 1,
      title: 'First Meet',
      date: '2018',
      description: 'Met at a coffee shop on a rainy Sunday morning. It was fate.',
      image: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&h=600&fit=crop',
    },
    {
      id: 2,
      title: 'First Date',
      date: '2018',
      description: 'Our first date was watching the sunset at the beach. Pure magic.',
      image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=600&h=600&fit=crop',
    },
    {
      id: 3,
      title: 'Proposal',
      date: '2022',
      description: 'Got down on one knee under the stars. She said YES!',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop',
    },
    {
      id: 4,
      title: 'Engagement',
      date: '2023',
      description: 'Celebrated our engagement with loved ones. Dreams coming true.',
      image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&h=600&fit=crop',
    },
  ],
  socialLinks: {
    instagram: 'https://instagram.com',
    facebook: 'https://facebook.com',
    twitter: 'https://twitter.com',
    pinterest: 'https://pinterest.com',
  },
  accommodations: [
    {
      id: 1,
      name: 'Luxury Resort & Spa',
      distance: '2 km away',
      phone: '+1-800-LUXURY1',
      website: 'https://example.com',
      specialRate: '20% discount for wedding guests',
    },
    {
      id: 2,
      name: 'boutique Hotel',
      distance: '1.5 km away',
      phone: '+1-800-LUXURY2',
      website: 'https://example.com',
      specialRate: '15% discount for wedding guests',
    },
  ],
  dresscode: 'Black Tie Optional',
  mealOptions: ['Vegetarian', 'Non-Vegetarian', 'Vegan', 'Gluten-Free'],
  thankyouMessage:
    'We are thrilled to share this special day with you. Your love, blessings, and support mean the world to us. Let\'s create memories together!',
};

export default coupleData;
